### ISSUE TITLE
non-existing media url

### ISSUE THREAD

**Issue by mayukojpn** [jawordpressorg/theme-test-data-ja#10]
Most `attachment_url` columns refer non-existing url http://kassad-tekapo.sqale.jp then this xml file cannot import media.

e.g. current [L216](https://github.com/jawordpressorg/theme-test-data-ja/blob/3735163b554b7d61922156a9707c90aba4c64f4f/wordpress-theme-test-date-ja.xml#L216) is:
`<wp:attachment_url>http://kassad-tekapo.sqale.jp/wp-content/uploads/2010/08/spectacles1.gif</wp:attachment_url>`

This will work (replaced by original Theme Unit Test xml file.)
`<wp:attachment_url>https://wpthemetestdata.files.wordpress.com/2014/01/spectacles.gif</wp:attachment_url>`

**Comment by tekapo** [comment]
FTTB, let's replace the urls. Could you send us the pull request, or I will do that in my spare time.

**Comment by tekapo** [comment]
Fixed. Please try it out. If you find something wrong, send a pull request or let me know! @mayukojpn
