### ISSUE TITLE
「投稿フォーマット: 画像」のデータが壊れています

### ISSUE THREAD

**Issue by DriftwoodJP** [jawordpressorg/theme-test-data-ja#15]
「この壁紙がほんとに大好きです。ジェーンの優しさを思い出す……。」のキャプションが外れて表示されています。

![2017-08-25 15 36 50](https://user-images.githubusercontent.com/3795425/29702324-c5c74c80-89ab-11e7-9a09-1d9d55f96460.png)

```html
<dl class="wp-caption aligncenter" id="attachment_612" style="width:650px;">
<dt class="wp-caption-dt"></dt>
</dl>
<p><img class="alignnone size-full wp-image-967" alt="ユニコーンの壁紙" src="http://wpthemetestdata.files.wordpress.com/2012/12/unicorn-wallpaper.jpg" width="1600" height="1200" /></p>
<p>この壁紙がほんとに大好きです。<a title="Jane" href="http://example.com/" target="_blank">ジェーン</a>の優しさを思い出す……。</p>
```

データに空の改行が含まれているからでしょうか？

https://github.com/jawordpressorg/theme-test-data-ja/blob/53012b2f787db8bbef3fb127acdc640b7b0aaa4b/wordpress-theme-test-date-ja.xml#L11995

修正方法が分からず報告だけで申し訳ないです。

**Comment by tekapo** [comment]
2年も放置しててゴメンナサイ。。

`<dt class="wp-caption-dt"></dt>`のことですよね?

元の英語版でも
`  <content:encoded><![CDATA[<dl id="attachment_612" class="wp-caption aligncenter" style="width:650px;"><dt class="wp-caption-dt"></dt></dl>&nbsp;`
https://github.com/WPTRT/theme-unit-test/blob/master/themeunittestdata.wordpress.xml#L8740
となっているので、キャプションのテキストがない場合を想定しているのではないでしょうか?

**Comment by DriftwoodJP** [comment]
ご確認ありがとうございました。
